run:
  # concurrency: 4
  timeout: 5m
  issue-exit-code: 1
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - example

output:
  format: colored-line-number

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
    ignore-tests: true
  goimports:
    local-prefixes: github.com/lsytj0413/golang-project-template

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - gocritic
    - godot
    - gofmt
    - goimports
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - goconst
    - unparam
    - cyclop
    - decorder
    - dupl
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - goerr113
    - goheader
    - lll

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
  fix: true